name: Keycloak CI

on:
  push:
    branches-ignore:
      - main
      - dependabot/**
  pull_request:
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"
  SUREFIRE_RERUN_FAILING_COUNT: 2
  SUREFIRE_RETRY: "-Dsurefire.rerunFailingTestsCount=2"

concurrency:
  # Only cancel jobs for PR updates
  group: ci-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:

  conditional:
    name: Check conditional workflows and jobs
    runs-on: ubuntu-latest
    outputs:
      ci: ${{ steps.conditional.outputs.ci }}
      ci-quarkus: ${{ steps.conditional.outputs.ci-quarkus }}
      ci-store: ${{ steps.conditional.outputs.ci-store }}
      ci-sssd: ${{ steps.conditional.outputs.ci-sssd }}
      ci-webauthn: ${{ steps.conditional.outputs.ci-webauthn }}
      ci-aurora: ${{ steps.auroradb-tests.outputs.run-aurora-tests }}
      ci-compatibility-matrix: ${{ steps.version-compatibility.outputs.matrix }}
    permissions:
      contents: read
      pull-requests: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: conditional
        uses: ./.github/actions/conditional
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: AuroraDB conditional check
        id: auroradb-tests
        run: |
          RUN_AURORADB_TESTS=false
          if [[ $GITHUB_EVENT_NAME != "pull_request" && -n "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]]; then
            RUN_AURORADB_TESTS=true
          fi
          echo "run-aurora-tests=$RUN_AURORADB_TESTS" >> $GITHUB_OUTPUT

      - name: Version Compatibility Matrix
        id: version-compatibility
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH="${{ github.base_ref }}"
          else
            BRANCH="${{ github.ref_name }}"
          fi
          MATRIX_JSON=$(./.github/scripts/version-compatibility.sh "${BRANCH}")
          echo "${MATRIX_JSON}"
          echo "matrix=${MATRIX_JSON}" >> $GITHUB_OUTPUT

  build:
    name: Build
    if: needs.conditional.outputs.ci == 'true'
    runs-on: ubuntu-latest
    needs: conditional
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak

      - name: Check for unstaged proto.lock files
        if: github.event_name == 'pull_request' && startsWith(github.event.pull_request.base.ref, 'release/')
        run: git diff --name-only --exit-code -- "**/proto.lock"

  quarkus-unit-tests:
    name: Quarkus UT
    needs: [build, conditional]
    if: needs.conditional.outputs.ci-quarkus == 'true'
    timeout-minutes: 15
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # We want to download Keycloak artifacts
      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      - name: Run unit tests
        run: |
          ./mvnw test -f quarkus/pom.xml -pl '!tests,!tests/junit5,!tests/integration,!dist'

      - name: Upload JVM Heapdumps
        if: always()
        uses: ./.github/actions/upload-heapdumps

      - name: Surefire reports
        if: always()
        uses: ./.github/actions/archive-surefire-reports
        with:
          job-id: quarkus-unit-tests-${{ matrix.os }}

  quarkus-integration-tests:
    name: Quarkus IT
    needs: [build, conditional]
    timeout-minutes: 115
    strategy:
      matrix:
        os: [ubuntu-latest]
        suite: [zip-slow, zip-fast, container, storage, smoke]
        full-testsuite:
          - ${{ needs.conditional.outputs.ci-quarkus == 'true' }}
        # Win runs always as includes are evaluated after excludes
        include:
          - os: windows-latest
            suite: win
        # Either run smoke tests, or full testsuite
        exclude:
          - full-testsuite: false
            suite: zip-slow
          - full-testsuite: false
            suite: zip-fast
          - full-testsuite: false
            suite: container
          - full-testsuite: false
            suite: storage
          - full-testsuite: true
            suite: smoke
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      MAVEN_OPTS: -Xmx1536m
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - id: integration-test-setup
        name: Integration test setup
        uses: ./.github/actions/integration-test-setup

      # Smoke tests should cover scenarios that could be broken by changes in other modules that quarkus
      # test classes and even individual tests are included in the following suites by junit tags
      # kc.quarkus.tests.groups acts as the tag filter
      - name: Run Quarkus integration Tests
        run: |
          declare -A PARAMS
          PARAMS["win"]="-Dkc.quarkus.tests.groups=win"
          PARAMS["zip-slow"]="-Dkc.quarkus.tests.groups=slow"
          PARAMS["zip-fast"]='-Dkc.quarkus.tests.groups=!slow'
          PARAMS["container"]="-Dkc.quarkus.tests.dist=docker"
          PARAMS["storage"]="-Ptest-database"
          PARAMS["smoke"]="-Dkc.quarkus.tests.groups=smoke"

          if [ "${{ matrix.suite }}" == "container" ]; then
            ./mvnw install -pl quarkus/tests/integration -am -DskipTests
          fi
          ./mvnw test -pl quarkus/tests/integration ${PARAMS["${{ matrix.suite }}"]} 2>&1 | misc/log/trimmer.sh

      - name: Upload JVM Heapdumps
        if: always()
        uses: ./.github/actions/upload-heapdumps

      - name: Surefire reports
        if: always()
        uses: ./.github/actions/archive-surefire-reports
        with:
          job-id: quarkus-integration-tests-${{ matrix.os }}-${{ matrix.suite }}

  check:
    name: Status Check - Keycloak CI
    if: always()
    needs:
      - conditional
      - build
      - quarkus-unit-tests
      - quarkus-integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/status-check
        with:
          jobs: ${{ toJSON(needs) }}
