name: OWASP

on: 
  workflow_dispatch:

env:
  MAVEN_ARGS: "-B -nsu -Daether.connector.http.connectionMaxTtl=25"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  analysis:
    name: OWASP dependency-check
    runs-on: ubuntu-latest
    if: github.repository == 'keycloak/keycloak'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Build Keycloak
        uses: ./.github/actions/build-keycloak
      - name: OWASP dependency-check
        run: ./mvnw -e --no-transfer-progress dependency-check:check
